### ISSUE TITLE
do not hardcode the .emacs dir

### ISSUE THREAD

**Issue by hyiltiz** [Open-App-Library/Sanemacs#4]
Right now it assumes `~/.emacs.d` is where it resides, but it could may well be `~/.emacs.d.sanemacs/` and someone could call emacs slightly differently.

**Comment by DougBeney** [comment]
Late response! Notification must've missed my inbox. Sorry about that. Good tip. I'll implement a fix.

**Comment by DougBeney** [comment]
fixed!
